# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

deploy:
  - provider: script
    script: ./docker-build --verbose --config .travis.yml --release github
    skip_cleanup: true
    on:
      tags: true
      condition: "${TRAVIS_TAG} =~ ^v.*$ && ${DISTRO} =~ ^fedora.*$"

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:30"
  - DISTRO="ubuntu:19.04"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-menus
    - gcc
    - git
    - glib2
    - gobject-introspection
    - intltool
    - make
    - mate-common
    - python2
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-menus
    - git
    - gobject-introspection
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - make
    - mate-common

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-menus.git
    - chrpath
    - gcc
    - git
    - gobject-introspection-devel
    - make
    - mate-common
    - python2-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - gobject-introspection
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - make
    - mate-common

variables:
  - CFLAGS="-Wall -Werror=format-security"

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-menus-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
